# Task for Today:

You are given a csv file containing:
name,maths,science,english,dept

requirement:
read csv file,
add new column total,
add a column average
find: top 3 studnets based on total
dept wise average marks
students scoring above 75 in all subjects
handle missing values(if any)

In [2]:
import pandas as pd
df = pd.read_csv("student_marks.csv")
print(df.columns)

Index(['name', 'maths', 'science', 'english', 'dept'], dtype='str')

In [3]:
df["Total"] = df["english"] + df["maths"] + df["science"]

In [4]:
df["Average"] = df["Total"]/3

In [5]:
df.sort_values(by="Average",ascending=False)[:3]

            name  maths  science  english dept  Total    Average
29    Tanvi Shah     97       96       98  CSE    291  97.000000
9   Ananya Gupta     96       94       95  CSE    285  95.000000
19    Ishita Sen     94       93       96  CSE    283  94.333333

In [27]:
df["Average"] = df[["maths","science","english"]].mean(axis=1)

top3_dept = (
    df.sort_values(["dept","Average"], ascending=[True,False])
      .groupby("dept")
      .head(3)[["name","dept","Average"]]
)
top3_dept

               name dept    Average
7       Meera Joshi   CE  76.333333
13     Pooja Mishra   CE  75.666667
23      Shreya Bose   CE  74.000000
29       Tanvi Shah  CSE  97.000000
9      Ananya Gupta  CSE  95.000000
19       Ishita Sen  CSE  94.333333
11      Neha Kapoor  ECE  89.000000
1        Riya Patel  ECE  88.000000
21       Nikita Roy  ECE  87.000000
27    Reshma Pillai  EEE  87.000000
17       Divya Nair  EEE  86.000000
4        Arjun Nair  EEE  78.333333
25      Lavanya Rao   IT  93.666667
15     Kavya Shetty   IT  93.000000
5        Priya Iyer   IT  86.666667
14  Aditya Kulkarni   ME  83.000000
24      Deepak Rana   ME  80.666667
2       Karan Verma   ME  72.333333